### ISSUE TITLE
Perte de connexion wifi

### ISSUE THREAD

**Issue by pyrech** [342apps/teleinfokit#10]
Salut,

Déjà, merci pour ton module qui est très pratique ! :yellow_heart: 

Malheureusement, je rencontre un soucis avec : régulièrement (en moyenne une fois par semaine je dirais), il arrête de transmettre des informations à home assistant (via MQTT). Quand je vais voir le module dans ces moments là, je remarque qu'il reboot en boucle et n'arrive pas à passer l'étape de la connexion wifi (le démarrage bloque à l'étape "Connexion au réseau wifi..", puis finit par reboot au bout d'un peu plus d'une minute).

Le module étant dans mon placard électrique avec la box wifi + la passerelle Zigbee, j'ai d'abord pensé à un soucis d'interférences qui pertuberait l'ESP. Mais même en éloignant le module à + 6m, ça ne change rien.

Je me suis également dit que l'ESP avait peut-etre un soucis de température et chauffait trop et finissait par se mettre en sécurité. Mais même en le laissant reposer plusieurs heures, toujours pareil lors du démarrage.

Est-ce que c'est un problème qui te parle ? Est-ce qu'il y a un moyen de debugger l'ESP pour comprendre ce qu'il se passe ? Est-ce que je peux/dois tenter de le mettre à jour pour espérer corriger le soucis ?

Merci :pray:

**Comment by pyrech** [comment]
Ok, j'ai compris le soucis. J'ai les wifi 2.4 et 5 GHz chez moi avec le band steering d'activé (meme config / ssid / mdp pour les 2 réseaux). Ce [thread du forum de Home Assistant](https://community.home-assistant.io/t/esp8266-weird-wifi-issues/50484/19) explique que les ESP8266 ont souvent des soucis avec ce type de config :disappointed: 

J'ai donc désactivé cette option dans ma box wifi (et coupé mon réseau 5 GHz au passage) et le boitier s'est reconnecté immédiatement. Peut-être qu'un avertissement pourrait être ajouté dans la doc, si d'autres gens ont le soucis ?

**Comment by nicop4** [comment]
Hello @pyrech !

Merci à toi ! J'ai aussi constaté des reboots et des utilisateurs remontent également ce souci, avec différents niveaux d'importance. De mon côté c'est anecdotique (une poignée de fois en tout).

Je pensais aussi à des perturbation radio car c'est assez chargé chez moi avec multiples réseaux wifi 2,4 et 5GHz, zigbee, Zwave...

Ta piste sur le conflit de band sterling est super intéressante ! Je vais voir si je peux jouer la dessus de mon coté. Je laisse l'issue ouverte en attendant d'analyser

**Comment by vmath54** [comment]
Problème similaire pour moi.

Fonctionnement impeccable du teleinfokit pendant près de 2 mois. Puis, sans que rien ne l'explique, le boitier ne se connecte plus au wifi, et part en boot sans arrêt.
J'ai tenté de le désalimenter électriquement plusieurs heures, puis de déplacer le boitier proche de ma box internet ; pareil.
J'ai appliqué la procédure de ré-initialisation. J'arrive bien sur le hotspot telekit. Dans la page 'Configure Wifi', les infos de connexion wifi ont été effacées, mais les infos MQTT sont toujours présentes.
Le scan wifi fonctionne. Je choisis mon ssid, je rentre le mot de passe, je sauvegarde. Le teleinfokit reboot, mais continue à booter en boucle.
J'ai tenté la manip à plusieurs reprises, toujours pareil.
Je précise que le boitier n'est plus raccordé au compteur linky, pour me faciliter les manips ; je ne pense pas que c'est cela qui pose problème.

Chez moi, les wifi 2.4Ghz et 5G ont des SSID différents. Il n'y a pas de gros trafic wifi dans mon habitation.

**Comment by satesting** [comment]
Bonjour,

Je confirme que l’utilisation du «steering» pose un problème au module, même avec un réseau dédié en 2,4Ghz only ceci ne suffit pas. (test réalisé sur UnifiOS)

Depuis plus d’un mois, je ne constate plus de coupure.

Merci pour votre travail à tous les deux  🙏

**Comment by nicop4** [comment]
Concernant les pertes de connexion wifi la root cause n'est pas clairement identifiée, même si des pistes se sont dessinées. 
Le nouveau firmware v2 utilise une version plus récente de la librairie WiFiManager, qui ne m'a causé aucun reboot depuis que je l'utilise. 
Je recommande donc de passer sur cette nouvelle version du firmware.
