### ISSUE TITLE
Pas d'update au reboot

### ISSUE THREAD

**Issue by welcoMattic** [342apps/teleinfokit#12]
Mon teleinfokit est toujours en v0.6, et au reboot il ne lance pas l'update vers la v1.0.0
Comment puis-je la forcer en OTA ?

**Comment by welcoMattic** [comment]
J'ai flashé à la main en wifi

**Comment by nicop4** [comment]
Hello @welcoMattic 
Il n'y a pas de mécanisme de mise à jour automatique, ni d'alerte en cas de nouvelle version disponible, le plus simple pour cela est de mettre le repository en favori ("Star" bouton) sur GitHub ;)
