### ISSUE TITLE
Plus aucune data ne remonte dans le Teleinfokit

### ISSUE THREAD

**Issue by welcoMattic** [342apps/teleinfokit#13]
Depuis quelques jours/semaines c'est encéphalogramme plat sur mon téléinfokit. Je n'arrive pas à savoir d'où ça vient (du Linky ou du téléinfokit), une idée pour m'aider à debug ça ? cc @pyrech

**Comment by nicop4** [comment]
Hello @welcoMattic 

Est-ce que tu as pu vérifier si le module est bien connecté à son wifi ? 
Il faut remonter les causes possibles :
Si les données de consommation ne s'affichent pas sur l'écran du module, le problème vient de la lecture des données TIC, donc voir le branchement avec le compteur.
Sinon vérifier à l'aide du dashboard web ou l'API si les données sont visible ici. 
Si c'est le cas, c'est probablement un problème avec le serveur MQTT auquel le module n'arrive pas à se connecter.

**Comment by welcoMattic** [comment]
Hello, à priori c'était le compteur qui ne renvoyait plus rien depuis les bornes I1 et I2. C'est revenu depuis. Étrange.
