### ISSUE TITLE
Gestion des forfaits un peu différents

### ISSUE THREAD

**Issue by Jeoffreybauvin** [342apps/teleinfokit#14]
Bonsoir !

Je suis récemment passé sur un nouveau contrat chez EDF : au lieu d'avoir des HC/HP classiques, j'ai : 
- HC toute la journée du mercredi, et tout le weekend
- HC/HP classiques le reste de la semaine

Seulement, coté teleinfokit, il semble bloqué sur la conso BASE : 

![image](https://user-images.githubusercontent.com/701928/197363075-1fc67e20-d52f-47c4-a713-fc0b7be21a8e.png)

![image](https://user-images.githubusercontent.com/701928/197363080-5b1e3d63-b65a-49df-a9ab-c85b4206654c.png)

![image](https://user-images.githubusercontent.com/701928/197363085-fb5eb7ee-1c52-4e3d-8e4a-6034b23238c0.png)

Une idée sur ce que je pourrais faire pour avoir les bonnes valeurs ?

Cordialement,

**Comment by nicop4** [comment]
Bonjour @Jeoffreybauvin 

La partie dashboard, dans l'onglet compteur affiche les données "classiques" en effet (index base et HP/HC), d'une manière un peu arbitraire, car je l'ai créé au tout début du projet ou il ne gérait que ce type de contrat classique.

Par contre si vous avez un firmware avec la version v1.0.0.6bbff8, celui ci va remonter en MQTT toutes les valeurs transmises par le compteur, donc y compris vos index spécifiques, et vous pouvez donc les utiliser dans Home Assistant par exemple. 
Je ne retrouve pas d'étiquette qui pourraient correspondre à vos photos dans la documentation Enedis, pourriez vous me dire ce qui remonte en MQTT (le nom des topics)?

![image](https://user-images.githubusercontent.com/10168765/197874847-2c7cc009-6c8e-47d2-b0a2-f4bf85a396d6.png)

Ensuite pour rendre le dashboard dynamique, il faudrait prévoir une petite évolution pour afficher la liste de valeurs réelle plutôt que les index que j'ai mis "en dur".

J'essaierai de proposer une nouvelle version avec cette fontionnalité ;)

**Comment by Jeoffreybauvin** [comment]
Bonjour @nicop4 ,

Tout d'abord merci pour la réponse.

Pour le dashboard, ce n'est pas un drame si vous me dites que c'est bien censé remonter dans mqtt.

Voici ce que j'ai :

![image](https://user-images.githubusercontent.com/701928/198013131-efc7826b-da3f-4811-ab4e-f2dd7cf2059a.png)

**Comment by Jeoffreybauvin** [comment]
Par contre, à cet instant je suis en HC tout le mercredi, et je vois seulement le topic BASE s'incrémenter. Normal ?

**Comment by Airliquide76** [comment]
Bonjour même soucis ici avec une option vert week end : HP/HC comme tout le monde puis HC tous le week end. Malgré ces options je n'ai que le base qui s'incrémente. Je pense que le soucis viens du fait que l'OPTTARIF remonté est BASE alors que ce n'est pas le cas. Je suis pourtant en mode TIC je devrais tout avoir ;) Y'a t'il on moyen de connecter un debug du port serie en live pour y lire les trames ? Version du firmeware : version v1.0.0.6bbff8

**Comment by nicop4** [comment]
En fait le boitier joue le rôle de d'adapteur série de ce qu'envoie le compteur : c'est du "format série", mais sur un signal différent (les signaux d’information sont de type « modulation d’amplitude » sur une porteuse à 50 kHz, et pas 0 ou 1 directement).
Ensuite tout ça est poussé en MQTT. Vous pouvez vous brancher sur la broche RX du [PCB](https://github.com/342apps/teleinfokit-board) (le hardware récent a un peu évolué, il faut que je mette à jour mais le brochage n'a pas changé) pour lire avec un dongle usb-série par exemple, mais ce sera exactement ce que reçoit l'ESP :)
J'ai déjà fait ce test, on retrouve bien ce qui est remonté par MQTT.

Par contre de ce qu'on voit c'est que des trames TIC sont mal décodées car on voit remonter des étiquettes erronées (comme les multiples variantes de MOTDETAT). Je vous invite a bien vérifier que les borniers sont bien vissés, et si possible utiliser du cable téléphonique torsadé, c'est ce qui est recommandé dans les specs ENEDIS.

En revanche c'est en effet étrange que seul BASE s'incrémente, mais il n'y a pas vraiment d'intelligence particulière dans le firmware à ce niveau la, on remonte vraiment tout tel quel (et même les trames mal décodées, cf. MOTDETAT). 
Il est vraisemblable que le compteur envoie des informations via TIC pas en concordance avec le contrat et que c'est le distributeur d'énergie qui se débrouille pour la facturation. 
Question subsidiaire : à l'écran de votre compteur, linky ou autre, est-ce que les index attendus s'affichent correctement ?

**Comment by nicop4** [comment]
Pour détailler un peu mieux, la question de savoir si les index s'affichaient correctement à l'écran du compteur était pour @Airliquide76, pour @Jeoffreybauvin on voit sur vos photos à l'écran du linky des "étiquettes" qui n'existent pas dans la [spec TIC ENEDIS](https://www.enedis.fr/media/2035/download)... ce qui peut expliquer que la répartition des index fournis par le TIC soit autre...

**Comment by Airliquide76** [comment]
Hello

Merci pour ton retour oui sur mon linky on retrouve bien les index qui s'incrémentent comme attendu. Avec des "étiquettes" pas gérées dans la doc enedis en effet ! Mais si pas de traitement coté esp particulier il y'a peu de raison que cela ne marche pas.

Je vais creuser coté décodage ;)

1 nov. 2022 22:20:43 nicop4 ***@***.***>:

**Comment by Jeoffreybauvin** [comment]
Hello,

Effectivement, je constate la meme chose que @Airliquide76 . Curieux de d'avoir un retour de ta part sur le sujet ;).

**Comment by nicop4** [comment]
Avec les dernières versions du firmware, toutes les informations issues du compteurs sont remontées par MQTT.
Ces infos peuvent être utilisées selon les besoin dans Home Assistant par exemple.

En revanche si les infos ne sont pas envoyées par le signal TIC, il ne sera pas possible de les obtenir. Je n'ai pas l'info de savoir si les fournisseurs peuvent personnaliser les données du compteur envoyées par la TIC ou affichées à l'écran.

Etant donné que ces données ne sont pas modifiables pas les utilisateurs, je clos cette issue, mais si besoin d'info complémentaire, ne pas hésiter à ajouter cela à la discussion.
