### ISSUE TITLE
Avoir tous les sensors 

### ISSUE THREAD

**Issue by chuppito** [342apps/teleinfokit#16]
Bonjour, actuellement, je n'ai que les 3 informations de l'exemple qui remonte (index, intensité instantanée et puissance consommée).
J'aimerais bien mettre :
Index injection

Est il possible d'avoir également, je doute, la puissance instantanée injectée.

Merci

**Comment by Gohad** [comment]
Bonjour,

Je suis du même avis, si nous pouvions récupérer la partir injectée via le module.
Je crois que le code dans la trame est EAIT.

**Comment by nicop4** [comment]
Bonjour

A partir de la version [v1.0.0.6bbff8](https://github.com/342apps/teleinfokit/releases/tag/v1.0.0.6bbff8) le firmware va remonter sur le serveur MQTT toutes les trames envoyées par le compteur via la TIC. 

Si votre module n'est pas sur la dernière version vous pouvez le mettre à jour en wifi. Voir la [doc associée](https://342apps.net/flashage-du-teleinfokit/) pour ca. 

Si la donnée qui vous intéresse n'y est pas c'est qu'elle n'est pas remontée par le compteur. 

La partie inconnue pour moi est comment est paramétré le compteur (par enedis ou le fournisseur d'électricité) pour activer tel ou tel tag en particulier. 

Je parle ici bien du firmware Teleinfokit de ce repo. Si vous êtes sur un firmware ESPHome c'est différent il faut ajouter le tag qui vous intéresse manuellement (et il faut que le compteur l'envoie sans quoi cela ne fera rien).  Mais dans ce cas merci d'ouvrir une discussion sur le repository dédié. 

Je clôture donc cette issue car le besoin est déjà implémenté dans le dernier firmware.

**Comment by chuppito** [comment]
Bonjour merci je vais essayer. Je ne suis pas sur esphome, eu besoin je peux essayer d'y passer s'il y a un tuto.
Merci

**Comment by nicop4** [comment]
Pour passer d'un firmware teleinfokit à ESPHome il faut flasher directement l'ESP01 via un adaptateur USB.
Mais si le firmware téléinfokit ne remonte pas le tag, il ne pourra pas plus être récupéré par ESPHome :)

**Comment by chuppito** [comment]
J'ai fait la mise à jour, l'info d'injection ne revient pas.
Pour Esphome par USB, il faut le faire via visual studio ?
Merci

**Comment by pbranly** [comment]
Je n'utilise plus le téléinfokit car j'ai tout porté sur un ESP32.
Mais il n'y a aucune raison que le téléinfokit flashé en esphome ne remonte pas toutes les trames tempo.
Pour info voilà ce que je remonte
Phil![image](https://user-images.githubusercontent.com/22018509/222277724-c92656d3-18c7-48d2-ab33-c7afe1c6c5cd.jpeg)

**Comment by chuppito** [comment]
Ok merci, si quelqu'un peut m'expliquer comment le flasher en Esphome pour que je test ça.
Merci

**Comment by pbranly** [comment]
De mémoire c'est explique dans la doc de @nicop4 . Il faut l'ouvrir pour accéder directement à l'esp. mais je ne l'ai pas fait perso .
Ceci dit, tu peux utiliser le dernier soft non esphome . Il donne toutes les trames tempo .

**Comment by chuppito** [comment]
J'ai un forfait de base et un index injection. C'est le seul qu'il me manque 
![Screenshot_20230301-232439](https://user-images.githubusercontent.com/10908251/222279413-195b115a-1a53-449d-9acb-f6006e7aee20.png)
