### ISSUE TITLE
mise à jours

### ISSUE THREAD

**Issue by vgeannin** [342apps/teleinfokit#18]
Bonjour,
J'ai ton boîtier en version hw 2 et firmware "1.0.0.6bbff8"
est-ce qu'il est compatible avec le firmware 2 ?

si oui quel est la procédure pour le mettre à jours ?

Merci

**Comment by nicop4** [comment]
Bonjour
Oui il est possible de faire la mise à jour du firmware V1 vers le firmware V2. La version hardware ne joue pas.

Les différences entres les firmwares et les compatibilités sont décrites sur la [page dédiée du site 342apps.net](https://342apps.net/teleinfokit-v4/) (en bas de la page).

A noter qu'en firmware V2, la page avec le dashboard et l'api REST ne sont plus fournies par le boitier (cf la [release note du firmware V2](https://github.com/342apps/teleinfokit/releases)).

La [procédure de flashage](https://342apps.net/flashage-du-teleinfokit/) également. La procédure de flashage une fois passé en firmware v2 est très légèrement différente (il n'y a plus la partie **Système de fichier**, juste la partie **Firmware**), je dois la mettre à jour.
