### ISSUE TITLE
il subsiste 2 messages en dehors de teleinfokit/data

### ISSUE THREAD

**Issue by pbranly** [342apps/teleinfokit#9]
bonjour,
MAJ 1.0 effectuée 
voir ecran mqt
![2021-11-15_11-08](https://user-images.githubusercontent.com/22018509/141764082-401ed5c9-d9d6-4d47-b656-4d25bf73ab52.png)
t

**Comment by nicop4** [comment]
Hello @pbranly 

Merci pour ta remontée d'info! 

Aujourd'hui c'est normal de toujours avoir les données "classiques" dans le topic `teleinfokit` pour des raisons de rétro-compatibilité avec les précédents firmware et la configuration qui a été faite avec ceux-ci.
Sans cela ce serait un breaking change et il faudrait modifier la config du côté des consommateurs des messages MQTT (Home Assistant, Telegraf, etc...).

Le topic `teleinfokit/data` offre toutes les données pour une intégration plus poussée si besoin.
On a en effet des données "dupliquées" mais ce n'est pas un problème majeur.

**Comment by pbranly** [comment]
Ok Nico
Faut il modifier la configuration telegraf ?

**Comment by nicop4** [comment]
Tu n'es pas obligé, c'est comme tu le souhaites.
Niveau stratégie pour le firmware cela restera ainsi jusqu'à une version 2 où potentiellement je ne laisserai que les données de `teleinfokit/data`
Mais pas encore de date en prévision!
